In [22]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

import smarts_cerebellum.globals as gl

In [23]:
p_df = pd.read_csv(os.path.join(gl.baseDir, 'participants.tsv'), sep = '\t')
p_df = p_df[~(p_df.subj_id.isin(gl.bad))]
p_df = p_df.drop_duplicates(subset = ['subj_id'])
patients = p_df[p_df.isPatient == 1]
controls = p_df[p_df.isPatient == 0]

In [24]:
patients.describe()

,SN,ID,week,numrun,nslices,lesionside,lesionlocation,age,handedness,isPatient,glm,surf_quality,surfmvpa,include1,lesiondef,behavior_missing,behavior_blocks,has_mvc,DTImap_missing,CentreNo
count,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.0,39.0,39.000000,39.0,39.000000,39.0,39.000000,39.000000,39.000000,39.000000,39.000000
mean,76.051282,2882.358974,1.538462,7.205128,33.256410,1.641026,2.000000,55.410256,1.743590,1.0,1.0,0.256410,1.0,0.846154,1.0,0.179487,7.025641,0.948718,0.025641,2.512821
std,44.723683,340.077119,2.989861,1.360717,2.009424,0.485971,0.760886,12.920237,0.442359,0.0,0.0,0.677377,0.0,0.365518,0.0,0.601393,1.784247,0.223456,0.160128,0.683328
min,1.000000,2282.000000,0.000000,4.000000,31.000000,1.000000,1.000000,22.000000,1.000000,1.0,1.0,0.000000,1.0,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,1.000000
25%,38.000000,2586.000000,0.000000,7.000000,31.000000,1.000000,1.000000,47.500000,1.500000,1.0,1.0,0.000000,1.0,1.000000,1.0,0.000000,6.500000,1.000000,0.000000,2.000000
50%,74.000000,2925.000000,0.000000,8.000000,35.000000,2.000000,2.000000,56.000000,2.000000,1.0,1.0,0.000000,1.0,1.000000,1.0,0.000000,8.000000,1.000000,0.000000,3.000000
75%,114.500000,3226.500000,4.000000,8.000000,35.000000,2.000000,3.000000,64.500000,2.000000,1.0,1.0,0.000000,1.0,1.000000,1.0,0.000000,8.000000,1.000000,0.000000,3.000000
max,153.000000,3248.000000,12.000000,8.000000,35.000000,2.000000,3.000000,80.000000,2.000000,1.0,1.0,2.000000,1.0,1.000000,1.0,3.000000,8.000000,1.000000,1.000000,3.000000

In [25]:
controls.describe()

,SN,ID,week,numrun,nslices,lesionside,lesionlocation,age,handedness,isPatient,glm,surf_quality,surfmvpa,include1,lesiondef,behavior_missing,behavior_blocks,has_mvc,DTImap_missing,CentreNo
count,10.000000,10.000000,10.0,10.0,10.000000,10.0,10.0,10.000000,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.000000
mean,185.800000,1003.700000,0.0,8.0,31.800000,0.0,0.0,62.600000,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,8.0,1.0,1.0,2.600000
std,17.472518,2.668749,0.0,0.0,1.686548,0.0,0.0,8.194849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.699206
min,158.000000,1001.000000,0.0,8.0,31.000000,0.0,0.0,52.000000,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,8.0,1.0,1.0,1.000000
25%,172.500000,1001.250000,0.0,8.0,31.000000,0.0,0.0,56.250000,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,8.0,1.0,1.0,2.250000
50%,187.500000,1003.000000,0.0,8.0,31.000000,0.0,0.0,61.500000,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,8.0,1.0,1.0,3.000000
75%,198.750000,1005.750000,0.0,8.0,31.000000,0.0,0.0,67.750000,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,8.0,1.0,1.0,3.000000
max,210.000000,1008.000000,0.0,8.0,35.000000,0.0,0.0,76.000000,2.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,8.0,1.0,1.0,3.000000