# MNISym_coreg_regression

**Pipeline**

Using full-image coregistered anatomicals with their segementations normalized to MNI Symmetric template:

- run regression on each of: wm, gm, T1, csf

- for subjects with left hemisphere lesion, flip (along x-axis, L-R flip) their slope image
    
    - slope image for each of wm, gm, T1, csf

- get the average image for patients and controls

In [1]:
# Imports

# need path to root directory
import sys
sys.path.append('/home/UWO/mporwal2/Documents/GitHub/smarts_cerebellum/')

# model libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# image reading libraries
import nibabel as nib
from nilearn import plotting as npl

import nitools as nt
from smarts_cerebellum import regression
from image_processing import overall_image
from image_processing import mirror_lesion
from pipelines import MNISym_coreg_regression
from image_processing import tissue_extractor as te
import smarts_cerebellum.globals as gl

from pathlib import Path
import os

In [2]:
# directories
p_df = pd.read_csv('/cifs/diedrichsen/data/smarts_cerebellum/participants_anat.tsv', sep = '\t')

## Regression

Perform regression on CSF segmentations normalized to MNISym template

In [19]:
# regression on CSF segmentations
MNISym_coreg_regression.subj_unique_regression_MNISym_coreg(type = 'CSF')

Regression on CU_2310

Regression on CU_2538

Regression on CU_2663

Regression on CU_2697

Regression on CU_2925

Regression on JHU_2282

Regression on JHU_2374

Regression on JHU_2395

Regression on JHU_2531

Regression on JHU_2577

Regression on JHU_2650

Regression on JHU_2684

Regression on JHU_2713

Regression on JHU_2789

Regression on JHU_3175

Regression on JHU_3176

Regression on UZ_2365

Regression on UZ_2450

Regression on UZ_2565

Regression on UZ_2595

Regression on UZ_2652

Regression on UZ_2654

Regression on UZ_2906

Regression on UZ_3030

Regression on UZ_3057

Regression on UZ_3151

skipping W4
Regression on UZ_3158

skipping W52
Regression on UZ_3166

Regression on UZ_3224

Regression on UZ_3226

Regression on UZ_3227

skipping W4
Regression on UZ_3228

Regression on UZ_3238

Regression on UZ_3239

Regression on UZ_3240

Regression on UZ_3241

Regression on UZ_3243

Regression on UZ_3246

Regression on UZ_3247

Regression on UZ_3248

Regression on CUP_1001

Regression on CUP_1002

Regression on JHP_1001

Regression on JHP_1002

Regression on JHP_1004

Regression on UZP_1001

Regression on UZP_1002

Regression on UZP_1004

Regression on UZP_1005

Regression on UZP_1006

Regression on UZP_1007

skipping W12
Regression on UZP_1008

skipping W12

## Mean slope

In [ ]:
patients_df = p_df[p_df.isPatient==1]
controls_df = p_df[p_df.isPatient==0]

# use affine from MNISym template

template_path = '/home/UWO/mporwal2/Documents/GitHub/smarts_cerebellum/tpl-MNI152NLin2009cSymC_T1w.nii'
template_img = nib.load(template_path)
template_affine = template_img.affine

### MNISym CSF

In [20]:
# patients

type = 'CSF'
subDir = 'mean_images'
stat_type = 'mean'
group = 'patients'

slope_patients = MNISym_coreg_regression.mean_image_right(df = patients_df, suffix = f'MNISym_{type}_coreg_reslice_slope')

slope_patients_img = nib.Nifti1Image(slope_patients, template_affine)
# save image with affine of template

nib.save(slope_patients_img, f'{base_dir}/Regression/{subDir}/{group}_MNISym_{type}_coreg_slope_{stat_type}.nii')

skipped CU_2697
skipped JHU_2374
skipped UZ_3228

In [21]:
# controls

type = 'CSF'
subDir = 'mean_images'
stat_type = 'mean'
group = 'controls'

slope_controls = MNISym_coreg_regression.mean_image_right(df = controls_df, suffix = f'MNISym_{type}_coreg_reslice_slope')

slope_controls_img = nib.Nifti1Image(slope_controls, template_affine)
# save image with affine of template

nib.save(slope_controls_img, f'{base_dir}/Regression/{subDir}/{group}_MNISym_{type}_coreg_slope_{stat_type}.nii')

## Median slope

In [ ]:
patients_df = p_df[p_df.isPatient==1]
controls_df = p_df[p_df.isPatient==0]

# use affine from MNISym template

template_path = '/home/UWO/mporwal2/Documents/GitHub/smarts_cerebellum/tpl-MNI152NLin2009cSymC_T1w.nii'
template_img = nib.load(template_path)
template_affine = template_img.affine

### MNISym CSF

In [22]:
# patients

type = 'CSF'
subDir = 'median_images'
stat_type = 'median'
group = 'patients'

slope_patients = MNISym_coreg_regression.median_image_right(df = patients_df, suffix = f'MNISym_{type}_coreg_reslice_slope')

slope_patients_img = nib.Nifti1Image(slope_patients, template_affine)
# save image with affine of template

nib.save(slope_patients_img, f'{base_dir}/Regression/{subDir}/{group}_MNISym_{type}_coreg_slope_{stat_type}.nii')

skipped CU_2697
skipped JHU_2374
skipped UZ_3228

In [23]:
# controls

type = 'CSF'
subDir = 'median_images'
stat_type = 'median'
group = 'controls'

slope_controls = MNISym_coreg_regression.median_image_right(df = controls_df, suffix = f'MNISym_{type}_coreg_reslice_slope')

slope_controls_img = nib.Nifti1Image(slope_controls, template_affine)
# save image with affine of template

nib.save(slope_controls_img, f'{base_dir}/Regression/{subDir}/{group}_MNISym_{type}_coreg_slope_{stat_type}.nii')

## Make a summarized dataframe for ROIs
Where ROIs are defined in the SUIT

In [3]:
search_path = os.path.join(gl.baseDir, 'Regression')

# files to include in summarized dataframe
suffixes = [
    'MNISym_CSF_coreg_reslice_slope.nii.gz',
    'MNISym_WM_coreg_reslice_slope.nii.gz',
    'MNISym_GM_coreg_reslice_slope.nii.gz',
    'MNISym_T1_coreg_reslice_slope.nii.gz'
]

In [4]:
p_df

,SN,ID,Centre,Week,week,RefT1,numrun,nslices,Hand,LesionSide,...,surfmvpa,include1,lesiondef,behavior_missing,behavior_blocks,has_mvc,DTImap_missing,CentreNo,machine,subj_id
0,1,2310,CU,W0,0,W0,8,35,b,left,...,1,1,1,0,8,0,0,1,naveed,CU_2310
1,2,2310,CU,W4,4,W0,8,35,b,left,...,1,1,1,0,8,0,0,1,naveed,CU_2310
2,3,2310,CU,W12,12,W0,8,35,b,left,...,1,1,1,0,8,1,0,1,naveed,CU_2310
3,4,2310,CU,W24,24,W0,8,35,b,left,...,1,1,1,0,8,1,0,1,naveed,CU_2310
4,5,2310,CU,W52,52,W0,8,35,b,left,...,1,1,1,3,0,1,0,1,naveed,CU_2310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,1008,UZP,W0,0,W0,8,31,b,none,...,1,1,0,0,8,1,1,3,eberlot,UZP_1008
210,211,1008,UZP,W4,4,W0,8,31,b,none,...,1,1,0,0,8,1,1,3,eberlot,UZP_1008
211,212,1008,UZP,W12,12,W0,8,31,b,none,...,1,1,0,0,8,1,1,3,eberlot,UZP_1008
212,213,1008,UZP,W24,24,W0,8,31,b,none,...,1,1,0,0,8,1,1,3,eberlot,UZP_1008
213,214,1008,UZP,W52,52,W0,8,31,b,none,...,1,1,0,0,8,1,1,3,eberlot,UZP_1008

In [5]:
summarized_df = te.make_summarized_dataframe(p_df = p_df,
                                             search_path = search_path,
                                             suffixes = suffixes,
                                             the_atlas = 'Diedrichsen_2009',
                                             maps = 'atl-Anatom',
                                             space = 'MNISym'
                                             )

Writing data for CU_2310
Writing data for CU_2538
Writing data for CU_2663
Writing data for CU_2925
Writing data for JHU_2282
Writing data for JHU_2395
Writing data for JHU_2531
Writing data for JHU_2577
Writing data for JHU_2650
Writing data for JHU_2684
Writing data for JHU_2713
Writing data for JHU_2789
Writing data for JHU_3175
Writing data for JHU_3176
Writing data for UZ_2365
Writing data for UZ_2450
Writing data for UZ_2565
Writing data for UZ_2595
Writing data for UZ_2652
Writing data for UZ_2654
Writing data for UZ_2906
Writing data for UZ_3030
Writing data for UZ_3057
Writing data for UZ_3151
Writing data for UZ_3158
Writing data for UZ_3166
Writing data for UZ_3224
Writing data for UZ_3226
Writing data for UZ_3227
Writing data for UZ_3238
Writing data for UZ_3239
Writing data for UZ_3240
Writing data for UZ_3241
Writing data for UZ_3243
Writing data for UZ_3246
Writing data for UZ_3247
Writing data for UZ_3248
Writing data for CUP_1001
Writing data for CUP_1002
Writing data for JHP_1001
Writing data for JHP_1002
Writing data for JHP_1004
Writing data for UZP_1001
Writing data for UZP_1002
Writing data for UZP_1004
Writing data for UZP_1005
Writing data for UZP_1006
Writing data for UZP_1007
Writing data for UZP_1008

In [ ]:
summarized_df

,image,image_name,frame,region,regionname,volume,atlas,map,space,mean,...,subj_id,ID,Centre,RefT1,age,Gender,isPatient,LesionSide,LesionLocation,handedness
0,1,CU_2310_MNISym_CSF_coreg_reslice_slope.nii.gz,0,1,Left_I_IV,4567.0,Diedrichsen_2009,atl-Anatom,MNISym,-0.000177,...,CU_2310,2310.0,CU,W0,57.0,M,1.0,left,subcortical,2.0
1,1,CU_2310_MNISym_CSF_coreg_reslice_slope.nii.gz,0,2,Right_I_IV,5524.0,Diedrichsen_2009,atl-Anatom,MNISym,0.000065,...,CU_2310,2310.0,CU,W0,57.0,M,1.0,left,subcortical,2.0
2,1,CU_2310_MNISym_CSF_coreg_reslice_slope.nii.gz,0,3,Left_V,5854.0,Diedrichsen_2009,atl-Anatom,MNISym,-0.000009,...,CU_2310,2310.0,CU,W0,57.0,M,1.0,left,subcortical,2.0
3,1,CU_2310_MNISym_CSF_coreg_reslice_slope.nii.gz,0,4,Right_V,5975.0,Diedrichsen_2009,atl-Anatom,MNISym,0.000108,...,CU_2310,2310.0,CU,W0,57.0,M,1.0,left,subcortical,2.0
4,1,CU_2310_MNISym_CSF_coreg_reslice_slope.nii.gz,0,5,Left_VI,12898.0,Diedrichsen_2009,atl-Anatom,MNISym,-0.000046,...,CU_2310,2310.0,CU,W0,57.0,M,1.0,left,subcortical,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6659,4,UZP_1008_MNISym_T1_coreg_reslice_slope.nii.gz,0,30,Right_Dentate,2197.0,Diedrichsen_2009,atl-Anatom,MNISym,-1.731406,...,UZP_1008,1008.0,UZP,W0,63.0,M,0.0,none,none,2.0
6660,4,UZP_1008_MNISym_T1_coreg_reslice_slope.nii.gz,0,31,Left_Interposed,255.0,Diedrichsen_2009,atl-Anatom,MNISym,-1.445008,...,UZP_1008,1008.0,UZP,W0,63.0,M,0.0,none,none,2.0
6661,4,UZP_1008_MNISym_T1_coreg_reslice_slope.nii.gz,0,32,Right_Interposed,277.0,Diedrichsen_2009,atl-Anatom,MNISym,-1.595848,...,UZP_1008,1008.0,UZP,W0,63.0,M,0.0,none,none,2.0
6662,4,UZP_1008_MNISym_T1_coreg_reslice_slope.nii.gz,0,33,Left_Fastigial,2.0,Diedrichsen_2009,atl-Anatom,MNISym,-0.639360,...,UZP_1008,1008.0,UZP,W0,63.0,M,0.0,none,none,2.0
6663,4,UZP_1008_MNISym_T1_coreg_reslice_slope.nii.gz,0,34,Right_Fastigial,5.0,Diedrichsen_2009,atl-Anatom,MNISym,-0.361079,...,UZP_1008,1008.0,UZP,W0,63.0,M,0.0,none,none,2.0

In [11]:
# save the dataframe

summarized_df.to_csv(f'{search_path}/MNISym_coreg_slope_AtlasSUIT_summarized.tsv', mode = 'w', sep = '\t', index = False, header = True)

In [10]:
search_path

'/cifs/diedrichsen/data/smarts_cerebellum/Regression'

In [7]:
len(summarized_df.image_name.unique())

196

In [9]:
49*4

196